data_processing/insee/sirene/flux/task_functions.py

wait 0.5 sec between each call insee

[data_processing] [sirene] feat: prevent new rate limiting from api insee

---

data_processing/insee/sirene/flux/task_functions.py

Ajouter les variables `anneeEffectifsUniteLegale` et `anneeCategorieEntreprise` au flux des unités légales.

[data_processing][sirene] feat: add varibales `annee_tranche` and `annee_categorie` 

---

dgv/harvester/DAG.py

As a side effet, the resulting code is much more readable :)

Use Pierlou's get_all_from_api_query to paginate harvest sources

---

schema/scripts/schemas_consolidation/schemas_consolidation.py
utils/datagouv.py

- use utilitary function to parse data.gouv catalogue
- allow files from URL that don't have a required file extension as long as they have a specific `content-type` in the header

Better consolidation

---

dgv/metrics/DAG.py
dgv/metrics/task_functions.py

New log path is `haproxy-logs-29062023-slb-XX.tar.gz`.
Since the date isn't formatted as isoformat, we parse it.

New minio path for logs

---

schema/scripts/schemas_consolidation/schemas_consolidation.py

issue was found with [Gireve data](https://www.data.gouv.fr/fr/datasets/fichier-irve-gireve/) coming from transport.data.gouv proxy (no file extension in the URL)

DAG consolidation: rework file extensions

---

dgv/metrics/sql/create_tables.sql

We may want to refactor the wording, in order to have "download" instead of "visit"? The word order in `resources_nb_visit` or `monthly_visit_resource` isn't crystal clear either.
See example usage on https://github.com/opendatateam/udata-metrics/pull/8/commits/64f8ba48ec7ccd393def668cae93094292d273e0

Add resource downloads on dataset, organization and site views

---

config.py
meta/task_functions.py

Need to add the AIRFLOW_URL variable in Admin

[Meta DAG] fixed URLs

---

data_processing/irve/DAG.py
schema/DAG_schemas_consolidation.py
schema/scripts/schemas_consolidation/consolidation_upload.py
schema/scripts/schemas_consolidation/schemas_consolidation.py
utils/schema.py

- add schema extras to all resources that are related to a schema (requested by transports.data.gouv)
- use hydra's availability check to assess if validation is required => time saved and reduce workload for validata's API

DAG consolidation

---

dgv/monitoring/DAG-bizdev.py

[DAG bizdev] remove dev tests

---

dgv/monitoring/DAG-notification.py

https://github.com/etalab/data.gouv.fr/issues/1100

[DAG activité] ping on potential orga duplicate

---

schema/scripts/schema_website/task_functions.py

@maudetes petit pansement sur un gros bobo

[DAG schema-site] fix: mask API call to handle JSONDecodeError

---

data_processing/dvf/DAG.py
dgv/harvester/DAG.py
dgv/metrics/DAG.py
dgv/monitoring/DAG-bizdev.py
dgv/monitoring/DAG-digest.py
dgv/monitoring/DAG-moderation-utilisateur.py
schema/DAG_schemas_recommendations.py
utils/mails.py
utils/notebook.py

Solving this issue: https://github.com/etalab/datagouvfr_data_pipelines/issues/5

Remove custom operators

---

data_processing/insee/sirene/flux/task_functions.py

related to https://github.com/etalab/annuaire-entreprises-site/issues/659

[data_processing][sirene]feat: add caractereEmployeur etab and ul to flux insee

---

dgv/monitoring/DAG-bizdev.py
dgv/monitoring/DAG-digest.py
dgv/monitoring/digest.ipynb

[DAG bizdev] add user agents when crawling reuses

---

data_processing/irve/DAG.py
data_processing/irve/task_functions.py
utils/schema.py

and refactor geo process (now in task_functions) to always process the latest version (too costly to process more)

[DAGs consolidation] upload a stable version of the latest consolidation

---

utils/schema.py

sleep between uploads to prevent a 500 when uploading same file at same second

[DAG consolidation] sleep between uploads to prevent a 500

---

dgv/monitoring/DAG-bizdev.py

@clarisse if you want to ignore more reuses, you can add their ids to the list

[DAG bizdev] add a list of reuses to ignore in crawl

---

data_processing/elections/task_functions.py
utils/minio.py

Do not merge before:
- adding `python-magic` to `requirements.txt` in production
- adding `RUN apt-get install libmagic1 -y` to the Dockerfile for the lib to work properly

[DAG éléctions] guess mime type when sending to minio

---

data_processing/elections/DAG-mirroring.py
data_processing/elections/task_functions.py
utils/minio.py

dag: elections mirroring

---

data_processing/meteo/pg_processing/DAG.py
data_processing/meteo/pg_processing/task_functions.py
utils/download.py

[DAG postgres météo] Make everything async for parallel processing and deal with file diffs

---

dgv/monitoring/utils.py

It is useful to monitor spam user to check the markdown `about` field on top of the `website` dedicated field.
Only deal with inline markdown (see [stackoverflow regex reference](https://stackoverflow.com/questions/30734682/extracting-url-and-anchor-text-from-markdown-using-python/30738268#30738268) used).

Extract site from user about markdown for digest

---

dgv/metrics/task_functions.py

Make the column selection clear when dumping the dataframe in organization-outlinks.csv. The dataframe had two "id" columns that were conflicting. The bug arised following a dependency upgrade.
Also add retries when calling the Matomo API when it returns a 502. Currently 5 retries before raising an error.
Proof of fix:

[DAG metrics] Fix matomo catalog process

---

meta/task_functions.py

Add @hacherix tag to Mattermost notifications.

[DAG MATTERMOST NOTIFICATION] Add user tag

---

dgv/metrics/config.yaml
dgv/metrics/task_functions_test.py

[DGV.METREICS] Fix /api/2/datasets/resources/

---

data_processing/sante/finess/DAG.py
data_processing/sante/finess/README.md
data_processing/sante/finess/config/dgv.json
data_processing/sante/finess/task_functions.py
meta/config/config.json

> Don't merge before Feb 15th, as agreed with the producers
Requires `pymupdf`
I'm wondering whether the process where we parse the PDF to extract the structure is overkill 🤔 should we rather hardcode the columns and crash if the structure changes?

DAG Finess

---

maintenance/DAG_clean_logs_and_runs.py

[DAG maintenance] fix: logs path in prod

---

data_processing/carburants/task_functions.py
data_processing/dvf/task_functions.py
data_processing/elections/aggregation/task_functions.py
data_processing/elections/miom_mirroring/task_functions.py
data_processing/formation/task_functions.py
data_processing/geozones/task_functions.py
data_processing/insee/deces/task_functions.py
data_processing/insee/sirene/stock/task_functions.py
data_processing/meteo/ftp_processing/task_functions.py
data_processing/meteo/pg_processing/task_functions.py
data_processing/meteo/pnt_monitor/task_functions.py
data_processing/meteo/previsions_densemble/task_functions.py
data_processing/meteo/stats_meteo/task_functions.py
data_processing/rna/task_functions.py
data_processing/sante/controle_sanitaire_eau/task_functions.py
data_processing/sante/finess/task_functions.py
dgv/impact/task_functions.py
dgv/metrics/task.py
dgv/monitoring/DAG-bizdev.py
dgv/monitoring/hvd/task_functions.py
dgv/stats/task_functions.py
schema/website/task_functions.py
utils/datagouv.py
utils/download.py
utils/filesystem.py
utils/minio.py
utils/postgres.py
utils/schema.py

To unify our practices (I have checked all files where the utils are used, there shouldn't be crashes hopefully 🤞)

fix: force paths to end with a slash

---

utils/filesystem.py

Solve https://workflows.infra.data.gouv.fr/dags/dgv_metrics/grid?dag_run_id=manual__2025-03-11T13%3A14%3A29.325930%2B00%3A00&task_id=download_log&tab=logs

[UTILS.FILESYSTEM] Add content_type arg

---

data_processing/carburants/task_functions.py
data_processing/elections/miom_mirroring/task_functions.py
data_processing/geozones/task_functions.py
data_processing/insee/sirene/stock/task_functions.py
data_processing/meteo/pg_processing/task_functions.py
dgv/stats/task_functions.py
schema/website/task_functions.py
utils/datagouv.py
utils/download.py
utils/filesystem.py
utils/schema.py

When we download a list of Files, it may be more efficient to leave it as `download_files([...])` as we are using a single session for the batch

utils: polish file

---

data_processing/irve/task_functions.py
data_processing/meteo/pg_processing/task_functions.py
dgv/metrics/config.py
dgv/metrics/task_functions.py
dgv/monitoring/dashboard/task_functions.py
dgv/monitoring/digest/task_functions.py
schema/website/task_functions.py
utils/datagouv.py
utils/download.py
utils/filesystem.py
utils/grist.py
utils/mattermost.py
utils/minio.py
utils/postgres.py
utils/schema.py
utils/utils.py

⚠️ do not merge before migration to the new prod env is complete

New optional and union syntax

---

dgv/simplifions/task_functions.py

Closes https://linear.app/pole-api/issue/API2-427/utiliser-une-colonne-en-production-pour-ignorer-les-topics-non-prets

private topics management for simplifions

---

dgv/simplifions/task_functions.py

Closes https://linear.app/pole-api/issue/API2-445/ignore-not-visible-rows-of-reco-solutions

ignore recommendations which should not be visible on simplifions
